[pytest]
testpaths = tests
markers =
      e2e: tests requiring a deployed application
addopts =
    -ra
    --browser chromium
    --tracing retain-on-failure
    --screenshot only-on-failure
    --video retain-on-failure
